// Generated by LiveScript 1.2.0
var prelude, main;
prelude = require('prelude-ls');
main = function($scope, $http){
  $scope.data = {};
  return $http.get('quote.json').success(function(data){
    var k;
    for (k in data) {
      data[k] = prelude.unique(data[k]);
      if (data[k].length > 5) {
        data[k] = data[k].splice(0, 5);
      }
    }
    delete data['*'];
    $scope.data = data;
    return console.log(data);
  });
};